### PR TITLE
Added Demos

### PR DESCRIPTION
**Pull request by gunjan543**

### CODE REVIEW

**Comment by nickvidal** [comment]
Hi @gunjan543, would you mind adding an gitignore file please?

**Comment by gunjan543** [comment]
> Hi @gunjan543, would you mind adding an gitignore file please?

@nickvidal Done

**Comment by nickvidal** [comment]
And also deleting the unnecessary files please! 😊

**Comment by gunjan543** [comment]
> And also deleting the unnecessary files please! 😊

Sorry @nickvidal  I am unable to find one. Can you please specify the file names?

**Pull request closed without merging**
